add project description
TolyaDeveloper/Harhash-KI-39-coursework pull request #1
Opened 2023-03-09 15:58 UTC by TolyaDeveloper

2023-03-13 20:45 UTC, NULP-KI requested changes
Деталійзуй який це саме має бути термінал (cmd, bash, sh, power shell, .... )?
Напиши конкретні ~10 функцій які має підтримувати твоя утиліта і більш детально як вона має працювати. Було б добре якби вона була data-driven і мала якийсь конфігураційний файл який би задавав всі необхідні кроки на набір стандартних команд. 
Надіюся це не звийчайні 10 bash скриптів, бо це буде заслабо як для КП.

Наразі замало інформації щоб зрозуміти як саме виглядатиме програма.

2023-03-14 10:01 UTC, TolyaDeveloper commented
Щодо терміналу, то це будь-який термінал (адже програмка буде кросплатформенною).

Нехай буде запуск програми (програма буде написана на node.js) в шелі zsh:
`node index.js`

Далі з'являються опції:
_"Яку команду ви хочете виконати"_

- ffmpeg
- ansible
- man

Вибираємо наприклад **ffmpeg**
Тепер зявляються питання щодо цієї команди, наприклад

- width: <поле для вводу>
- height: <поле для вводу>
- inputName:  <поле для вводу>
- outputName: <поле для вводу>

Після введення формується строка: ffmpeg -i `inputName` -s `width`x`height` `outputName`
Далі запускається child process який також буде виконаний в zsh.
І виводиться результат.

Файл конфігурації буде не доречним, адже кожна команда може мати свою окрему логіку яка має бути описана.
Також реалізація цією програми **не буде** просто наївною (насправді сама наївна реалізація вийде десь думаю 50 строк коду).
Тому задля майбутнього **маштабування** будуть використані архітектурні патерни .

Буде написаний logger-service, prompt-service(введення даних), сервіс роботи з файлами, білдер та executor під кожну команду.

2023-03-14 21:21 UTC, NULP-KI commented
додайте цей опис у readme.md

2023-03-22 21:13 UTC, NULP-KI approved these changes

2023-03-24 14:50 UTC, merged