Add requirements.docx
TolyaDeveloper/Harhash-KI-39-coursework pull request #15
Opened 2023-04-19 14:57 UTC by TolyaDeveloper

2023-04-23 17:01 UTC, NULP-KI requested changes
1. п.1.2 розробників чого саме?
2. п.2.1. Не треба писати свою думку. Уявіть що ви представляєте компанію і пишете вимоги для того, щоб узгодити начинку продукту з замовником. Тут ніякої своє думки в цьому документі не може бути. Суто опис роботи продукту. 
3.  п. 3.2 не містить опису усіх команд. Можна описати меню. Формат команд можна не описувати.

2023-04-24 13:54 UTC, TolyaDeveloper commented
> 1. п.1.2 розробників чого саме?
> 
>     2. п.2.1. Не треба писати свою думку. Уявіть що ви представляєте компанію і пишете вимоги для того, щоб узгодити начинку продукту з замовником. Тут ніякої своє думки в цьому документі не може бути. Суто опис роботи продукту.
> 
>     3. п. 3.2 не містить опису усіх команд. Можна описати меню. Формат команд можна не описувати.

fixed

2023-05-03 19:26 UTC, NULP-KI commented
Функціональні вимоги не відображають усіх функцій програми.
Мало б бути якось так:

Взаємодія користувача з програмно має відбуватися за допомогою командного інтерфейсу користувача. Мають підтримуватися наступні команди:
- К1
- К2
- К3

Команда К1 робить .....
.......
При її виборі користувачу відображається підменю з командами:
-КП1
-КП2
-КП3

КП1 робить .......
.....
Інтерфейс користувача має мати опцію допомоги.

Програма має мати можливість інтеграцію з Telegram.

2023-05-07 08:21 UTC, TolyaDeveloper commented
> Функціональні вимоги не відображають усіх функцій програми. Мало б бути якось так:
> 
> Взаємодія користувача з програмно має відбуватися за допомогою командного інтерфейсу користувача. Мають підтримуватися наступні команди:
> 
>     * К1
> 
>     * К2
> 
>     * К3
> 
> 
> Команда К1 робить ..... ....... При її виборі користувачу відображається підменю з командами: -КП1 -КП2 -КП3
> 
> КП1 робить ....... ..... Інтерфейс користувача має мати опцію допомоги.
> 
> Програма має мати можливість інтеграцію з Telegram.

fixed

2023-05-09 01:16 UTC, NULP-KI commented
"Також реалізація програми не повинна буде “наївною”." - це видалити.
"Необхідна чітка архітектура з можливістю майбутнього масштабування або швидкої можливості інтеграції з іншими сервісами, наприклад Telegram (чат-бот)." - Перенести в пункт "Вимоги до інтеграції з сервісами сторонніх виробників"

2023-05-10 07:00 UTC, TolyaDeveloper commented
> "Також реалізація програми не повинна буде “наївною”." - це видалити. "Необхідна чітка архітектура з можливістю майбутнього масштабування або швидкої можливості інтеграції з іншими сервісами, наприклад Telegram (чат-бот)." - Перенести в пункт "Вимоги до інтеграції з сервісами сторонніх виробників"

fixed

2023-05-17 21:52 UTC, NULP-KI approved these changes

2023-05-18 06:52 UTC, merged